### ISSUE TITLE
Инструкция по установке

### ISSUE THREAD

**Issue by OlehTsvirko** [x0x01/astatum#1]
Здравствуйте. В статье на <a href="http://habrahabr.ru/post/229883">хабре</a> astatum приводится как альтернативный сервис отложенного чтения. Не могли бы вы более подробно расписать процесс его установки и настройки?
На главной странице я вижу ряд команд для установки, но не понимаю, куда их писать. Какое программное обеспечение необходимо для этого? Спасибо.

**Comment by Egorkat** [comment]
Привет! Нашел этот проект также в комментах на Хабре.
Установить на свой сервер смог, но вот заставить работать не вышло на 100%. Остались непонятки...
Было бы очень здорово сделать все по инструкции!!!

**Comment by Egorkat** [comment]
Олег, пока крутится барабан, может я могу помочь с установкой?
Спрашивайте!

**Comment by OlehTsvirko** [comment]
Насколько я понял astatum нужно установить на свой веб-сервер (хостинг) и привинтив кнопку в браузер отправлять туда страницы для обработки, а потом загружать по rss на любое устройство. Правильно?
Меня интересует сам процесс установки: какие файлы куда заливать, что прописывать в них и т.д.

**Comment by Egorkat** [comment]
Да, на свой сервак.
Я шел по этому пути:
$ mkdir /srv
$ cd /srv
$ git clone https://github.com/x0x01/astatum.git
$ cd astatum
$ chmod 777 static/img
$ pip install -r requirements.txt
Отредактировать config.py - тут были первые непонятки. Я оставил движок по умолчанию, включил и вписал RSS_Feed своего TinyTiny сервера.

$ python astatum.py - этой строкой Astatum стартует и слушает порт 8002. Вот там все совсем не ясно - вроде что-то он видит, но пользоваться не получается.

**Comment by OlehTsvirko** [comment]
Выходит я скачиваю все файлы архивом через DownloadZIP, заливаю их на свой сервер в корень, настраиваю config.py.
А что значат эти строки:
$ mkdir /srv
$ cd /srv
и т.д.
Если это что-то питоновское, то я в нем не силён.

**Comment by Egorkat** [comment]
Нет, скачивать руками не надо. Перечисленные команды делают это сами.
Все это делается в консоли сервера с правами рута.
$ mkdir /srv - делает папку srv в корне раздела
$ cd /srv - переходит в нее
$ git clone https://github.com/x0x01/astatum.git - качает файлы проекта в эту папку
$ cd astatum - переходим в свежую подпапку
$ chmod 777 static/img - меняем права
$ pip install -r requirements.txt - устанавливаются доп. пакеты

**Comment by OlehTsvirko** [comment]
Благодарю за разъеснения. Сейчас нет возможности, но как только попробую установить - отпишусь.

**Comment by x0x01** [comment]
Немного подправил описание установки. 
Настройки в config.py можно не менять, существующих достаточно для запуска приложения.
На самом деле каталог srv не принципиален, и служит в качестве примера (к нему привязаны настройки nginx и supervisor)

Для "на попробовать" на локальной машине, можно использовать такую последовательность команд:
```sh
$ cd ~
$ git clone https://github.com/x0x01/astatum.git
$ cd astatum
$ chmod 777 static/img
$ sudo pip install -r requirements.txt
$ python astatum.py
```
После чего, в браузере, перейти по ссылке http://127.0.0.1:8082/
